/**
 * Generates the source-of-truth cutover backfill migration from the bundled
 * catalog (src/data/bundledContent.ts). One-off generator; output is a normal
 * tracked, idempotent migration applied via scripts/run-migrations.ts.
 *
 * Usage: npx tsx scripts/generate-source-of-truth-backfill.ts
 */
import fs from 'fs';
import path from 'path';
import { getBundledArtworks, DEFAULT_HERO_SLUGS } from '../src/data/bundledContent';
import { INITIAL_PAGES } from '../src/data/driveFileSystem';

const OUT = path.resolve(process.cwd(), 'supabase', 'migrations', '2026_09_13_cms_v2_source_of_truth_backfill.sql');

/**
 * Bundled registry slug → DB slug. The bulk import renamed artworks to
 * title-derived slugs; the DB spelling is canonical (media_assets, prior
 * backfills, and dashboard PATCHes all use it).
 */
const SLUG_ALIASES: Record<string, string> = {
  '2010': '2010-rendezvous-in-chinatown',
  '78704': 'austin-78704-south-austin-zip',
  'austin-2019': 'austin-skyline-2019',
  'el-pajaro-de-los-dulces-magicos': 'el-p-jaro-de-los-dulces-m-gicos',
  'issy': 'issy-the-atomic-companion',
  'kelzon-5': 'kelzon-v',
  'regador-5': 'regador-v',
  'the-balloon-cats-2': 'the-balloon-cats-ii',
  'the-18000th-whole': 'the-18-000th-hole',
  'the-cats-of-the-colloseum': 'the-cats-of-the-colosseum',
  'the-martian-2': 'the-martian-ii',
  'today': 'today-atomic-sunrise',
  'wisdom-cofee': 'wisdom-coffee',
  // Legacy default-hero slug for the 2010 artwork
  'rendezvous-in-chinatown': '2010-rendezvous-in-chinatown',
};

const dbSlug = (bundledSlug: string): string => SLUG_ALIASES[bundledSlug] ?? bundledSlug;

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const artworks = getBundledArtworks();

const narrativeCases = artworks
  .map((a) => `    WHEN ${sqlString(dbSlug(a.slug))} THEN ${sqlString(a.narrative)}`)
  .join('\n');

const imageCases = artworks
  .map((a) => `    WHEN ${sqlString(dbSlug(a.slug))} THEN ${sqlString(a.imageRef)}`)
  .join('\n');

const heroValues = DEFAULT_HERO_SLUGS.map((s) => sqlString(dbSlug(s))).join(', ');

const pageValues = Object.entries(INITIAL_PAGES)
  .map(([filename, content]) => {
    const slug = filename.replace(/\.md$/, '');
    const title = slug.charAt(0).toUpperCase() + slug.slice(1);
    return `  (${sqlString(slug)}, ${sqlString(title)}, ${sqlString(content)})`;
  })
  .join(',\n');

const sql = `-- CMS v2 — Source-of-truth cutover backfill
-- Generated by scripts/generate-source-of-truth-backfill.ts from the bundled
-- catalog registry. Idempotent: fills EMPTY narratives only, replaces
-- placeholder image refs only, restores hero defaults only where false.
-- Apply with: npx tsx scripts/run-migrations.ts <this-file>

-- 1. Narrative backfill from the bundled catalog bodies (DB slugs canonical)
UPDATE public.artworks
SET narrative = CASE slug
${narrativeCases}
  END,
  updated_at = now()
WHERE narrative IS NULL OR narrative = '';

-- 1b. Graceful starter narrative for any row with no bundled content
UPDATE public.artworks
SET narrative = '# ' || title || E'\\n\\nOriginal painting from the Rory Skagen Studio catalog.',
    updated_at = now()
WHERE narrative IS NULL OR narrative = '';

-- 2. Image ref backfill: replace /images/N.svg placeholders with the real
--    image filename refs (clients resolve URLs via the asset resolver)
UPDATE public.artworks
SET image_url = CASE slug
${imageCases}
  END,
  updated_at = now()
WHERE image_url IS NULL OR image_url LIKE '/images/%';

-- 3. Restore the studio's default hero-slider selection
UPDATE public.artworks
SET hero_slider = true, updated_at = now()
WHERE slug IN (${heroValues}) AND hero_slider = false;

-- 4. Seed bundled pages (upsert; admin edits in the DB always win afterwards)
INSERT INTO public.pages (slug, title, content)
VALUES
${pageValues}
ON CONFLICT (slug) DO NOTHING;
`;

fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${OUT} (${(sql.length / 1024).toFixed(0)} KB, ${artworks.length} artworks, ${Object.keys(INITIAL_PAGES).length} pages)`);
