/**
 * Generates `src/data/releaseLog.generated.ts` from the project's two release-history documents.
 *
 * WHY A GENERATED ARTIFACT RATHER THAN A RUNTIME READ
 * The admin Changelog screen (v3.1.0, capability C1) shows `CHANGELOG.md` and `DEPLOYMENT_LOG.md`.
 * The obvious implementation — read the markdown at request time — is rejected for three reasons:
 *
 *   1. **The serverless bundle has no reliable disk.** `api/index.js` is a single esbuild bundle and
 *      nothing else in `server/` reads from disk, so `fs` at runtime is a packaging risk, not a
 *      convenience.
 *   2. **Parsing in the browser is worse.** It would put the whole changelog in the client bundle,
 *      and `src/data/assetRegistry.ts` is already ~987 KB (R-20) — the site's largest payload
 *      problem, which this must not add to.
 *   3. **An untestable I/O call in the middle of a decision.** `scripts/lib/seoPlan.ts` states the
 *      repo's rule: a decision made inside a script that talks to a database is a decision no test
 *      can reach. Here the same applies to a script that talks to the filesystem.
 *
 * So the parse happens at build time, the result is committed, and it is served by
 * `GET /api/plan/history`. This is the `generate-asset-registry.ts` → `src/data/assetRegistry.ts`
 * idiom, deliberately repeated.
 *
 * ⚠️ THE OUTPUT IS DETERMINISTIC — NO TIMESTAMP, NO BUILD ID.
 * That is load-bearing, not tidiness. The release checklist's staleness check is
 * `npx tsx scripts/generate-release-log.ts && git diff --exit-code`, and a timestamp would make
 * that fail on every run, which would train everyone to ignore it. `src/test/releaseLogSync.test.ts`
 * depends on the same property.
 *
 * Re-generate after either document changes:
 *   npx tsx scripts/generate-release-log.ts
 */

import fs from 'fs';
import path from 'path';
import { buildReleaseLog } from './lib/releaseLog';

const CHANGELOG = 'CHANGELOG.md';
const DEPLOYMENT_LOG = 'DEPLOYMENT_LOG.md';
const OUT = 'src/data/releaseLog.generated.ts';

const BANNER = `/**
 * AUTO-GENERATED by scripts/generate-release-log.ts — do not edit by hand.
 * Source of truth: ${CHANGELOG} and ${DEPLOYMENT_LOG}, both owned by the release process.
 * Re-generate after either changes:
 *   npx tsx scripts/generate-release-log.ts
 *
 * D1 (plan/ROADMAP_V3_1_TO_V3_3_FEEDBACK_AND_PLANNING.md): history is DERIVED, the plan is
 * AUTHORED. This is a read-only projection of the two documents — nothing in the studio writes
 * back to them, and the release notes a release drafts are never committed to ${CHANGELOG} by
 * the app.
 *
 * The output is deterministic (no timestamp) so that
 *   npx tsx scripts/generate-release-log.ts && git diff --exit-code
 * is a real staleness check, and src/test/releaseLogSync.test.ts can assert equality.
 */`;

/** The emitted module's source text, given the parsed log. Exported so the sync test can reuse it. */
export function renderArtifact(log: unknown): string {
  return [
    BANNER,
    '',
    "import type { ReleaseLog } from '../../scripts/lib/releaseLog';",
    '',
    // Re-exported so the browser can name the shape without reaching outside `src/`.
    // `src/components/admin/ChangelogView.tsx` renders this structure; importing the type from
    // here rather than from `scripts/lib/releaseLog` keeps every client-side import inside `src/`,
    // and a change to the parser's `ReleaseLog` still fails `npm run lint` at the view. Type-only,
    // so it costs the client bundle nothing.
    'export type { ReleaseLog };',
    '',
    `export const RELEASE_LOG: ReleaseLog = ${JSON.stringify(log, null, 2)};`,
    '',
  ].join('\n');
}

function main(): void {
  for (const file of [CHANGELOG, DEPLOYMENT_LOG]) {
    if (!fs.existsSync(file)) {
      console.error(`✗ ${file} is missing. Run this from the repository root.`);
      process.exit(1);
    }
  }

  const log = buildReleaseLog(
    fs.readFileSync(CHANGELOG, 'utf8'),
    fs.readFileSync(DEPLOYMENT_LOG, 'utf8')
  );

  const { releases, deploymentRows, warnings } = log.diagnostics;

  // A build that parsed nothing must not silently ship an empty history screen — the same
  // "abort rather than emit an empty artifact" rule scripts/prerender-seo.ts applies to artworks.
  if (releases === 0) {
    console.error(`✗ Parsed 0 releases out of ${CHANGELOG}. Refusing to write an empty history.`);
    process.exit(1);
  }
  if (deploymentRows === 0) {
    console.error(`✗ Parsed 0 deployment rows out of ${DEPLOYMENT_LOG}. Refusing to write.`);
    process.exit(1);
  }

  const outPath = path.resolve(OUT);
  const source = renderArtifact(log);
  fs.writeFileSync(outPath, source, 'utf8');

  // Self-verify, like scripts/backup-catalog.ts: re-read what was just written and confirm the
  // structure survives the round trip. A truncated write must fail here, not in the admin UI.
  const written = fs.readFileSync(outPath, 'utf8');
  const embedded = /\bRELEASE_LOG: ReleaseLog = ([\s\S]*);\s*$/.exec(written.replace(/\r\n/g, '\n'));
  if (!embedded) {
    console.error(`✗ ${OUT} was written but its payload could not be read back.`);
    process.exit(1);
  }
  let reparsed: unknown;
  try {
    reparsed = JSON.parse(embedded[1]);
  } catch (error) {
    console.error(`✗ ${OUT} contains invalid JSON: ${(error as Error).message}`);
    process.exit(1);
  }
  if (JSON.stringify(reparsed) !== JSON.stringify(log)) {
    console.error(`✗ ${OUT} does not round-trip — refusing to report success.`);
    process.exit(1);
  }

  console.log(`Wrote ${OUT}`);
  console.log(`  releases:         ${releases}`);
  console.log(`  deployment rows:  ${deploymentRows}`);
  console.log(`  sections:         ${log.changelog.reduce((n, r) => n + r.sections.length, 0)}`);
  console.log(`  entries:          ${log.changelog.reduce((n, r) => n + r.sections.reduce((m, s) => m + s.entries.length, 0), 0)}`);

  if (warnings.length) {
    console.warn(`\n⚠️  ${warnings.length} parse warning(s) — the documents may have changed shape:`);
    for (const warning of warnings) console.warn(`   • ${warning}`);
  } else {
    console.log('\nNo parse warnings.');
  }
}

// Only run when invoked directly, so the sync test can import `renderArtifact` without writing.
if (process.argv[1] && /generate-release-log/.test(process.argv[1])) {
  main();
}
