/**
 * PRD_V3_CLOUDINARY_EXIT.md — Stage v3.2.
 * Generates src/data/assetRegistry.ts from the public.media_assets table
 * (populated by scripts/migrate-cloudinary-to-supabase.ts in stage v3.1).
 *
 * The generated module is committed so the client bundle needs no network
 * fetch on cold start. Re-run after media changes:
 *   npx tsx scripts/generate-asset-registry.ts
 */

import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { Pool } from 'pg';
import { resolvePoolTarget } from './lib/pgTarget';

dotenv.config();

interface RenditionMeta {
  path: string;
  width: number;
  height: number;
  bytes: number;
}

interface RegistryRow {
  public_id: string;
  url: string;
  thumbnail_url: string;
  width: number;
  height: number;
  lqip: string | null;
  renditions: Record<string, RenditionMeta> | null;
  artwork_slug: string | null;
}

const SUPABASE_URL =
  process.env.VRCL_SUPA_SUPABASE_URL ||
  process.env.SUPABASE_URL ||
  'https://orphcusijzkxpxkzapjp.supabase.co';

function getConnectionString(): string {
  const raw =
    process.env.VRCL_SUPA_POSTGRES_PRISMA_URL ||
    process.env.VRCL_SUPA_POSTGRES_URL ||
    process.env.VRCL_SUPA_POSTGRES_URL_NON_POOLING ||
    '';
  if (!raw) throw new Error('PostgreSQL connection string missing from environment.');
  return raw.replace(/\?.*$/, '');
}

function publicUrl(relPath: string): string {
  return `${SUPABASE_URL}/storage/v1/object/public/artwork-images/${relPath}`;
}

async function main(): Promise<void> {
  // Loopback targets (the local scratch database on 127.0.0.1:54322) get no TLS — the SSL rule
  // lives in scripts/lib/pgTarget.ts. Remote behaviour is unchanged.
  const poolTarget = resolvePoolTarget(getConnectionString());
  const pool = new Pool({
    connectionString: poolTarget.connectionString,
    ssl: poolTarget.ssl,
  });

  const { rows } = await pool.query<RegistryRow>(
    `SELECT public_id, url, thumbnail_url, width, height, lqip, renditions, artwork_slug
       FROM public.media_assets
      WHERE renditions IS NOT NULL
      ORDER BY public_id`
  );

  await pool.end();

  if (rows.length === 0) {
    throw new Error('media_assets has no rows with renditions — run stage v3.1 migration first.');
  }

  // slug -> entry map. Primary key is the artwork_slug when present, so the
  // resolver can look up by artwork slug directly; public_id kept as fallback key.
  const entries = rows.map((r) => {
    const rends = (r.renditions ?? {}) as Record<string, RenditionMeta>;
    const rend = (name: string) => {
      const m = rends[name];
      return m ? { url: publicUrl(m.path), width: m.width, height: m.height, bytes: m.bytes } : null;
    };
    return {
      keys: [r.public_id, ...(r.artwork_slug ? [r.artwork_slug] : [])],
      thumb: rend('thumb'),
      hero: rend('hero'),
      full: rend('full'),
      lqip: r.lqip ?? null,
      srcWidth: r.width,
      srcHeight: r.height,
      artworkSlug: r.artwork_slug,
    };
  });

  const keyToEntry = new Map<string, (typeof entries)[number]>();
  for (const e of entries) {
    for (const k of e.keys) {
      const norm = k.toLowerCase();
      if (!keyToEntry.has(norm)) keyToEntry.set(norm, e);
      // Alias keys so slug-style lookups hit assets whose public_id uses
      // legacy filenames (e.g. artwork slug "greetings-from-austin" vs
      // public_id "GreetingsfromAustin"): normalized (alnum-only) forms and
      // dashed forms both resolve to the same entry.
      const alnum = norm.replace(/[^a-z0-9]/g, '');
      if (alnum && !keyToEntry.has(alnum)) keyToEntry.set(alnum, e);
      const dashed = norm.replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
      if (dashed && !keyToEntry.has(dashed)) keyToEntry.set(dashed, e);
    }
  }

  const fileHeader = `/**
 * AUTO-GENERATED by scripts/generate-asset-registry.ts — do not edit by hand.
 * Source of truth: public.media_assets (Supabase), populated by stage v3.1
 * migration from Cloudinary. Re-generate after media changes:
 *   npx tsx scripts/generate-asset-registry.ts
 *
 * PRD_V3_CLOUDINARY_EXIT.md — Stage v3.2.
 * Keys: asset public_id (lowercase) and artwork_slug where linked.
 * Supabase project: ${SUPABASE_URL}
 */

export interface AssetRendition {
  url: string;
  width: number;
  height: number;
  bytes: number;
}

export interface AssetRegistryEntry {
  keys: string[];
  thumb: AssetRendition | null;
  hero: AssetRendition | null;
  full: AssetRendition | null;
  /** Tiny webp data-URI for blur-up placeholders (null when absent). */
  lqip: string | null;
  srcWidth: number;
  srcHeight: number;
  artworkSlug: string | null;
}

`;

  const lines: string[] = [];
  lines.push(`export const ASSET_REGISTRY: Record<string, AssetRegistryEntry> = {`);
  for (const [key, e] of [...keyToEntry.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const rend = (r: { width: number; height: number; bytes: number; url: string } | null) =>
      r
        ? `{ url: ${JSON.stringify(r.url)}, width: ${r.width}, height: ${r.height}, bytes: ${r.bytes} }`
        : 'null';
    lines.push(`  ${JSON.stringify(key)}: {`);
    lines.push(`    keys: ${JSON.stringify(e.keys)},`);
    lines.push(`    thumb: ${rend(e.thumb)},`);
    lines.push(`    hero: ${rend(e.hero)},`);
    lines.push(`    full: ${rend(e.full)},`);
    lines.push(`    lqip: ${e.lqip ? JSON.stringify(e.lqip) : 'null'},`);
    lines.push(`    srcWidth: ${e.srcWidth},`);
    lines.push(`    srcHeight: ${e.srcHeight},`);
    lines.push(`    artworkSlug: ${e.artworkSlug ? JSON.stringify(e.artworkSlug) : 'null'},`);
    lines.push(`  },`);
  }
  lines.push(`};`);
  lines.push('');

  const outPath = path.resolve('src/data/assetRegistry.ts');
  fs.writeFileSync(outPath, fileHeader + lines.join('\n'), 'utf8');
  console.log(`assetRegistry.ts written: ${keyToEntry.size} keys from ${rows.length} media_assets rows -> ${outPath}`);
}

main().catch((err) => {
  console.error('ERROR:', err.message);
  process.exit(1);
});
