/**
 * The rendition ladder — one encoder, two callers.
 *
 * WHY THIS EXISTS
 * Until v2.16.0 the ladder lived *only* inside `scripts/migrate-cloudinary-to-supabase.ts`, so the
 * 151 assets that came over from Cloudinary had thumb/hero/full + lqip and the studio's own upload
 * route had nothing. `POST /api/media/upload` inserted `VALUES ($1, $2, $2, …)` — the same string
 * for `url` and `thumbnail_url`, no `renditions`, no `lqip` — which means every photo an admin
 * uploads today is served at full size in the gallery grid. That is a live studio bug, not a
 * migration leftover.
 *
 * The fix is to make the ladder shared rather than to write a second one. Two encoders is how the
 * migrated catalog and the studio's own uploads drift apart in quality, dimensions and object
 * layout — and the bucket layout is load-bearing: `src/data/assetRegistry.ts` (generated by
 * `scripts/generate-asset-registry.ts`) turns `renditions.{thumb,hero,full}.path` into the URLs the
 * public gallery renders, so `{publicId}/{name}.webp` is a contract, not a convenience.
 *
 * Owner decisions that bound this module (PRD §1):
 *   - **Q2** — v3 ingests Wayback images as a batch *pre-pass* at web quality. That pass is a third
 *     caller of this module; it does not go through the upload route.
 *   - **Q4** — full resolution is never needed in the studio, so `full` is capped (2048 px here) and
 *     the source bytes are **not** retained by the upload route.
 *
 * `sharp` is a runtime dependency: this module is imported by `server/routes/media.ts`, which runs
 * inside the Vercel serverless function, not by a CLI script.
 */
import sharp, { type Metadata, type Sharp } from 'sharp';

/**
 * The single place rendition sizes live (PRD §3.1 contract).
 *
 * `withoutEnlargement` is applied on every render: a 480 px source yields a 480 px `full`, never an
 * upscaled 2048 px one. That is why 79 of the 151 migrated assets have a `thumb` the same pixel size
 * as their `full` — the source is smaller than 640 px, not the ladder being broken.
 */
export const RENDITIONS = {
  thumb: { width: 640, quality: 80 },
  hero: { width: 1280, quality: 82 },
  full: { width: 2048, quality: 85 },
} as const;

export type RenditionName = keyof typeof RENDITIONS;

/** Stable iteration order for uploads and for the `renditions` document. */
export const RENDITION_NAMES = Object.keys(RENDITIONS) as RenditionName[];

/** Renditions are always WebP; the source format is recorded on the row, not in the object path. */
export const RENDITION_FORMAT = 'webp';
export const RENDITION_MIME = 'image/webp';

/** Blur-up placeholder: tiny enough to inline as a data URI on every grid card. */
export const LQIP_WIDTH = 20;
export const LQIP_QUALITY = 40;

/** One year, immutable. With no CDN (PRD Q3) browser caching is the entire egress strategy. */
export const IMMUTABLE_CACHE_CONTROL = '31536000';

/** The bucket every rendition is written to. */
export const MEDIA_BUCKET = 'artwork-images';

/**
 * Thrown when a buffer cannot be decoded as an image.
 *
 * Distinct from an infrastructure failure: this is the *caller's* file being unusable, so the upload
 * route answers 400 rather than 500 — a staff member re-exporting a corrupt file needs to be told
 * to try again, not to report a server bug.
 */
export class UnreadableImageError extends Error {
  constructor(message = 'Could not read image dimensions — the file is not a decodable image.') {
    super(message);
    this.name = 'UnreadableImageError';
  }
}

/** Shape stored in `media_assets.renditions` and consumed by the generated asset registry. */
export interface RenditionMeta {
  /** Object path within the bucket, e.g. `the-balloon-cats-ii/thumb.webp`. */
  path: string;
  width: number;
  height: number;
  bytes: number;
}

export interface RenderedImage {
  /** Dimensions of the *source* image, before any resizing. */
  width: number;
  height: number;
  /** Normalised source format (`jpg`, `png`, `webp`, `gif`, `avif`) — never `jpeg`. */
  format: string;
  /** `data:image/webp;base64,…` placeholder. */
  lqip: string;
  /** Keyed by rendition name; written verbatim to `media_assets.renditions`. */
  renditions: Record<RenditionName, RenditionMeta>;
  /** Encoded bytes, keyed by rendition name, in `RENDITION_NAMES` order. */
  buffers: Record<RenditionName, Buffer>;
}

/** Where a rendition object lives in the bucket. Consumed by the asset registry generator. */
export function renditionObjectPath(publicId: string, name: RenditionName): string {
  return `${publicId}/${name}.${RENDITION_FORMAT}`;
}

/**
 * `sharp` reports `jpeg`; the migrated catalog and the asset registry use `jpg`. One spelling, or
 * `format` becomes a column with two names for one thing.
 */
export function normalizeFormat(format: string | undefined): string {
  if (!format) return 'unknown';
  return format === 'jpeg' ? 'jpg' : format;
}

/**
 * Decode an image once and render the whole ladder from it.
 *
 * `rotate()` honours EXIF orientation before anything is resized, so a phone photo taken sideways
 * does not produce a sideways `full` with correctly-oriented thumbnails. `failOn: 'none'` keeps
 * slightly-truncated uploads from being rejected outright.
 *
 * ⚠️ `failOn: 'none'` does **not** cover `metadata()` — sharp still throws `Input buffer contains
 * unsupported image format` / `Input Buffer is empty` for undecodable input, so the read is wrapped
 * and re-thrown as `UnreadableImageError`. Anything that cannot report dimensions is rejected: a row
 * with no width/height cannot build an aspect-ratio box and would ship a broken gallery card.
 *
 * @throws `UnreadableImageError` if the buffer is not a decodable image.
 */
export async function renderRenditions(original: Buffer, publicId: string): Promise<RenderedImage> {
  let base: Sharp;
  let meta: Metadata;
  try {
    // The constructor throws on an empty buffer ("Input Buffer is empty"); `metadata()` throws on
    // undecodable bytes. Both mean the same thing to the caller, so both are caught here.
    base = sharp(original, { failOn: 'none' }).rotate();
    meta = await base.metadata();
  } catch (err) {
    throw new UnreadableImageError(
      `Could not decode image: ${err instanceof Error ? err.message : String(err)}`
    );
  }

  const width = meta.width ?? 0;
  const height = meta.height ?? 0;
  if (width <= 0 || height <= 0) {
    throw new UnreadableImageError();
  }

  const rendered = await Promise.all(
    RENDITION_NAMES.map(async (name) => {
      const { width: target, quality } = RENDITIONS[name];
      const { data, info } = await base
        .clone()
        .resize({ width: target, withoutEnlargement: true })
        .webp({ quality })
        .toBuffer({ resolveWithObject: true });

      return {
        name,
        buffer: data,
        meta: {
          path: renditionObjectPath(publicId, name),
          // `info` is measured from the encoded output, so it is the truth rather than an
          // arithmetic guess — and it is what `generate-asset-registry.ts` publishes.
          width: info.width ?? Math.min(target, width),
          height: info.height ?? 0,
          bytes: info.size ?? data.length,
        } satisfies RenditionMeta,
      };
    })
  );

  const lqipBuffer = await base
    .clone()
    .resize({ width: LQIP_WIDTH })
    .webp({ quality: LQIP_QUALITY })
    .toBuffer();

  return {
    width,
    height,
    format: normalizeFormat(meta.format),
    lqip: `data:image/${RENDITION_FORMAT};base64,${lqipBuffer.toString('base64')}`,
    renditions: Object.fromEntries(rendered.map((r) => [r.name, r.meta])) as Record<
      RenditionName,
      RenditionMeta
    >,
    buffers: Object.fromEntries(rendered.map((r) => [r.name, r.buffer])) as Record<
      RenditionName,
      Buffer
    >,
  };
}
