-- CMS v2 — Source-of-truth cutover backfill
-- Generated by scripts/generate-source-of-truth-backfill.ts from the bundled
-- catalog registry. Idempotent: fills EMPTY narratives only, replaces
-- placeholder image refs only, restores hero defaults only where false.
-- Apply with: npx tsx scripts/run-migrations.ts <this-file>

-- 1. Narrative backfill from the bundled catalog bodies (DB slugs canonical)
UPDATE public.artworks
SET narrative = CASE slug
    WHEN 'gianondor' THEN '[[index|← Return to Master Catalog Index]]

# Gianondor

![[gianondor.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2019-07-12
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-12. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'empopatya' THEN '[[index|← Return to Master Catalog Index]]

# Empopatya

![[empopatya.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2019-07-12
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-12. Rendered in Enamel (3.5ft x 5ft) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'gaurdon' THEN '[[index|← Return to Master Catalog Index]]

# Gaurdon

![[gaurdon.jpg]]

> **Kaiju & Monster Universe** — Produced 2019-07-12
> **Medium & Dimensions:** Enamel (33in x 4ft) • 33 × 48 in (84 × 122 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-12. Rendered in Enamel (33in x 4ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'gondoleu' THEN '[[index|← Return to Master Catalog Index]]

# Gondoleu

![[gondeoleu.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2019-07-12
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-12. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'jobar' THEN '[[index|← Return to Master Catalog Index]]

# Jobar

![[jobar.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2019-07-12
> **Medium & Dimensions:** Enamel (33in x 4ft) • 33 × 48 in (84 × 122 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-12. Rendered in Enamel (33in x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'kondowari' THEN '[[index|← Return to Master Catalog Index]]

# Kondowari

![[kondowari.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2019-07-12
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-12. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'meiwaku' THEN '[[index|← Return to Master Catalog Index]]

# Meiwaku

![[meiwaku.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2019-07-12
> **Medium & Dimensions:** Enamel (33in x 4ft) • 33 × 48 in (84 × 122 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-12. Rendered in Enamel (33in x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'odoroita-sakana' THEN '[[index|← Return to Master Catalog Index]]

# Odoroita Sakana

![[OdoritaSakana.jpg]]

> **Kaiju & Monster Universe** — Produced 2019-07-12
> **Medium & Dimensions:** Enamel (3ft x 4ft) • 36 × 48 in (91 × 122 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-12. Rendered in Enamel (3ft x 4ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'osore' THEN '[[index|← Return to Master Catalog Index]]

# Osore

![[osore.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2019-07-12
> **Medium & Dimensions:** Enamel (33in x 4ft) • 33 × 48 in (84 × 122 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-12. Rendered in Enamel (33in x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'austin-skyline-2019' THEN '[[index|← Return to Master Catalog Index]]

# Austin Skyline 2019

![[austin2019-copy.jpg]]

> **Austin Iconic & Pop Americana** — Produced 2019-07-11
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-11. Rendered in Enamel (3.5ft x 5ft) exploring themes of austin iconic & pop americana. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'kemuri' THEN '[[index|← Return to Master Catalog Index]]

# Kemuri

![[kemuri.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2019-07-11
> **Medium & Dimensions:** - (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Archived • **Surface:** Mixed media archival master

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-11. Rendered in signature mixed media (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-persistence-of-cats' THEN '[[index|← Return to Master Catalog Index]]

# The Persistence of Cats

![[2019cats-copy.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2019-07-11
> **Medium & Dimensions:** Enamel (33in x 4ft) • 33 × 48 in (84 × 122 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-11. Rendered in Enamel (33in x 4ft) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'today-atomic-sunrise' THEN '[[index|← Return to Master Catalog Index]]

# Today (Atomic Sunrise)

![[2019today-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2019-07-11
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-11. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'cyborg-robots-and-aliens' THEN '[[index|← Return to Master Catalog Index]]

# Cyborg: Robots and Aliens

![[robot-copy-1.jpg]]

> **Kaiju & Monster Universe** — Produced 2019-07-10
> **Medium & Dimensions:** Acrylic (3ft x 5ft) • 36 × 60 in (91 × 152 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-10. Rendered in Acrylic (3ft x 5ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-martian-ii' THEN '[[index|← Return to Master Catalog Index]]

# The Martian II

![[themartian2-copy.jpg]]

> **Kaiju & Monster Universe** — Produced 2019-07-10
> **Medium & Dimensions:** Acrylic (3ft x 5ft) • 36 × 60 in (91 × 152 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-10. Rendered in Acrylic (3ft x 5ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-martian' THEN '[[index|← Return to Master Catalog Index]]

# The Martian

![[themartian1-copy.jpg]]

> **Kaiju & Monster Universe** — Produced 2019-07-10
> **Medium & Dimensions:** Acrylic (3ft x 5ft) • 36 × 60 in (91 × 152 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2019-07-10. Rendered in Acrylic (3ft x 5ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-carters' THEN '[[index|← Return to Master Catalog Index]]

# The Carters

![[thecarters.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2018-03-14
> **Medium & Dimensions:** - (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Archived • **Surface:** Mixed media archival master

## Artwork Description

Original masterwork by Rory Skagen created on 2018-03-14. Rendered in signature mixed media (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'an-insincere-call' THEN '[[index|← Return to Master Catalog Index]]

# An Insincere Call

![[sound-of-the-WB-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2017-06-07
> **Medium & Dimensions:** Enamel (3ft x 4ft) • 36 × 48 in (91 × 122 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2017-06-07. Rendered in Enamel (3ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'arachforun' THEN '[[index|← Return to Master Catalog Index]]

# Arachforun

![[starwars-Recovered-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2017-06-07
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2017-06-07. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'gleesnod-and-collasaur' THEN '[[index|← Return to Master Catalog Index]]

# Gleesnod and Collasaur

![[octodino-Recovered-copy.jpg]]

> **Kaiju & Monster Universe** — Produced 2017-06-07
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2017-06-07. Rendered in Enamel (3.5ft x 5ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'gnarldred' THEN '[[index|← Return to Master Catalog Index]]

# Gnarldred

![[Steamy-the-flavor-genie-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2017-06-07
> **Medium & Dimensions:** Enamel (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2017-06-07. Rendered in Enamel (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'kelzon-v' THEN '[[index|← Return to Master Catalog Index]]

# Kelzon V

![[Jungle-bust-el-5-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2017-06-07
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2017-06-07. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'scaramouche' THEN '[[index|← Return to Master Catalog Index]]

# Scaramouche

![[Scaramouche-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2017-06-07
> **Medium & Dimensions:** Enamel (3ft x 4ft) • 36 × 48 in (91 × 122 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2017-06-07. Rendered in Enamel (3ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-broken-record' THEN '[[index|← Return to Master Catalog Index]]

# The Broken Record

![[brokenrecord-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2017-06-07
> **Medium & Dimensions:** Enamel (3ft x 4ft) • 36 × 48 in (91 × 122 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2017-06-07. Rendered in Enamel (3ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-greeting-card-machine' THEN '[[index|← Return to Master Catalog Index]]

# The Greeting Card Machine

![[greetingcardmachine-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2017-06-07
> **Medium & Dimensions:** Enamel (3ft x 5ft) • 36 × 60 in (91 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2017-06-07. Rendered in Enamel (3ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'austin-78704-south-austin-zip' THEN '[[index|← Return to Master Catalog Index]]

# Austin 78704 (South Austin Zip)

![[78704.jpg]]

> **Austin Iconic & Pop Americana** — Produced 2015-06-04
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-04. Rendered in Enamel (3.5ft x 5ft) exploring themes of austin iconic & pop americana. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'austin-postcard' THEN '[[index|← Return to Master Catalog Index]]

# Austin Postcard

![[austinpostcard.jpg]]

> **Austin Iconic & Pop Americana** — Produced 2015-06-04
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-04. Rendered in Enamel (3.5ft x 5ft) exploring themes of austin iconic & pop americana. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'greetings-from-austin' THEN '[[index|← Return to Master Catalog Index]]

# Greetings from Austin

![[GreetingsfromAustin.jpg]]

> **Austin Iconic & Pop Americana** — Produced 2015-06-04
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-04. Rendered in Enamel (3.5ft x 5ft) exploring themes of austin iconic & pop americana. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'greetings-from-texas' THEN '[[index|← Return to Master Catalog Index]]

# Greetings from Texas

![[GreetingsfromTexas.jpg]]

> **Austin Iconic & Pop Americana** — Produced 2015-06-04
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-04. Rendered in Enamel (3.5ft x 5ft) exploring themes of austin iconic & pop americana. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'jigoku' THEN '[[index|← Return to Master Catalog Index]]

# Jigoku

![[jigoku.jpg]]

> **Kaiju & Monster Universe** — Produced 2015-06-04
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-04. Rendered in Enamel (3.5ft x 5ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'kirunam' THEN '[[index|← Return to Master Catalog Index]]

# Kirunam

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2015-06-04
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-04. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'misakimo' THEN '[[index|← Return to Master Catalog Index]]

# Misakimo

![[k.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2015-06-04
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-04. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'terrordon' THEN '[[index|← Return to Master Catalog Index]]

# Terrordon

![[terrordon.jpg]]

> **Kaiju & Monster Universe** — Produced 2015-06-04
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-04. Rendered in Enamel (3.5ft x 5ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'utaho' THEN '[[index|← Return to Master Catalog Index]]

# Utaho

![[utaho.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2015-06-04
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-04. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'cry-sing-lon' THEN '[[index|← Return to Master Catalog Index]]

# Cry Sing Lon

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2015-06-03
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-06-03. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'austin-camouflage' THEN '[[index|← Return to Master Catalog Index]]

# Austin Camouflage

![[l.jpg]]

> **Austin Iconic & Pop Americana** — Produced 2015-01-29
> **Medium & Dimensions:** Enamel (22in x 5ft) • 22 × 60 in (56 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-29. Rendered in Enamel (22in x 5ft) exploring themes of austin iconic & pop americana. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'austin-carnival' THEN '[[index|← Return to Master Catalog Index]]

# Austin Carnival

![[r.jpg]]

> **Austin Iconic & Pop Americana** — Produced 2015-01-29
> **Medium & Dimensions:** Acrylic (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-29. Rendered in Acrylic (3.5ft x 5ft) exploring themes of austin iconic & pop americana. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'beat-bop' THEN '[[index|← Return to Master Catalog Index]]

# Beat Bop

![[beatbop.jpg]]

> **Modernist Parody & Fine Art Tribute** — Produced 2015-01-29
> **Medium & Dimensions:** Acrylic (19in x 5ft) • 19 × 60 in (48 × 152 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-29. Rendered in Acrylic (19in x 5ft) exploring themes of modernist parody & fine art tribute. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'jumbo-portions' THEN '[[index|← Return to Master Catalog Index]]

# Jumbo Portions

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2015-01-29
> **Medium & Dimensions:** Acrylic (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-29. Rendered in Acrylic (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'marcia-ball' THEN '[[index|← Return to Master Catalog Index]]

# Marcia Ball

![[r.jpg]]

> **Austin Iconic & Pop Americana** — Produced 2015-01-29
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-29. Rendered in Acrylic (4ft x 4ft) exploring themes of austin iconic & pop americana. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'pollack-jr' THEN '[[index|← Return to Master Catalog Index]]

# Pollack Jr.

![[pollockjr.jpg]]

> **Modernist Parody & Fine Art Tribute** — Produced 2015-01-29
> **Medium & Dimensions:** Enamel (3ft x 4ft) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-29. Rendered in Enamel (3ft x 4ft) exploring themes of modernist parody & fine art tribute. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-balloon-cats-ii' THEN '[[index|← Return to Master Catalog Index]]

# The Balloon Cats II

![[l.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2015-01-29
> **Medium & Dimensions:** Acrylic (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-29. Rendered in Acrylic (3.5ft x 5ft) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-teapot-ride' THEN '[[index|← Return to Master Catalog Index]]

# The Teapot Ride

![[r.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2015-01-29
> **Medium & Dimensions:** Acrylic (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-29. Rendered in Acrylic (3.5ft x 5ft) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'women-and-ladders' THEN '[[index|← Return to Master Catalog Index]]

# Women and Ladders

![[r.jpg]]

> **Modernist Parody & Fine Art Tribute** — Produced 2015-01-29
> **Medium & Dimensions:** Acrylic (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-29. Rendered in Acrylic (3.5ft x 5ft) exploring themes of modernist parody & fine art tribute. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'rothko-jr' THEN '[[index|← Return to Master Catalog Index]]

# Rothko Jr.

![[rothmonster-copy.jpg]]

> **Modernist Parody & Fine Art Tribute** — Produced 2015-01-28
> **Medium & Dimensions:** Acrylic (4ft x 3ft) • 48 × 36 in (122 × 91 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2015-01-28. Rendered in Acrylic (4ft x 3ft) exploring themes of modernist parody & fine art tribute. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'hatari-angani' THEN '[[index|← Return to Master Catalog Index]]

# Hatari Angani

![[art.svg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-09-16
> **Medium & Dimensions:** - (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Archived • **Surface:** Mixed media archival master

## Artwork Description

Original masterwork by Rory Skagen created on 2011-09-16. Rendered in signature mixed media (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'mao-mao-ting' THEN '[[index|← Return to Master Catalog Index]]

# Mao Mao Ting

![[art.svg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-09-16
> **Medium & Dimensions:** - (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Archived • **Surface:** Mixed media archival master

## Artwork Description

Original masterwork by Rory Skagen created on 2011-09-16. Rendered in signature mixed media (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'maakclops' THEN '[[index|← Return to Master Catalog Index]]

# Maakclops

![[art.svg]]

> **Kaiju & Monster Universe** — Produced 2011-09-16
> **Medium & Dimensions:** - (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Archived • **Surface:** Mixed media archival master

## Artwork Description

Original masterwork by Rory Skagen created on 2011-09-16. Rendered in signature mixed media (-) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'ocamehocta' THEN '[[index|← Return to Master Catalog Index]]

# Ocamehocta

![[art.svg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-09-16
> **Medium & Dimensions:** - (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Archived • **Surface:** Mixed media archival master

## Artwork Description

Original masterwork by Rory Skagen created on 2011-09-16. Rendered in signature mixed media (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'nangon-and-sadas' THEN '[[index|← Return to Master Catalog Index]]

# Nangon and Sadas

![[art.svg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-08-16
> **Medium & Dimensions:** - (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Archived • **Surface:** Mixed media archival master

## Artwork Description

Original masterwork by Rory Skagen created on 2011-08-16. Rendered in signature mixed media (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-end-of-austin' THEN '[[index|← Return to Master Catalog Index]]

# The End of Austin

![[f.jpg]]

> **Austin Iconic & Pop Americana** — Produced 2011-01-29
> **Medium & Dimensions:** Enamel (6ft x 4ft) • 72 × 48 in (183 × 122 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-29. Rendered in Enamel (6ft x 4ft) exploring themes of austin iconic & pop americana. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'adventures-in-illustration' THEN '[[index|← Return to Master Catalog Index]]

# Adventures in Illustration

![[adventures-in-illustration-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-28
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-28. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'heartbreak-forest' THEN '[[index|← Return to Master Catalog Index]]

# Heartbreak Forest

![[heartbreak-forest-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-28
> **Medium & Dimensions:** Acrylic (18in x 5ft) • 18 × 60 in (46 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-28. Rendered in Acrylic (18in x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'mid-flight-connection' THEN '[[index|← Return to Master Catalog Index]]

# Mid-Flight Connection

![[midflight-connection-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-28
> **Medium & Dimensions:** Acrylic (4ftx4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-28. Rendered in Acrylic (4ftx4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'quo-quan-dang' THEN '[[index|← Return to Master Catalog Index]]

# Quo Quan Dang

![[d.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-28
> **Medium & Dimensions:** Acrylic (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-28. Rendered in Acrylic (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-cat-bird-seat' THEN '[[index|← Return to Master Catalog Index]]

# The Cat Bird Seat

![[the-catbird-seat-copy.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-28
> **Medium & Dimensions:** Acrylic (4ft x 3ft) • 48 × 36 in (122 × 91 cm)
> **Status:** Archived • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-28. Rendered in Acrylic (4ft x 3ft) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-narrative' THEN '[[index|← Return to Master Catalog Index]]

# The Narrative

![[the-narrative.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-28
> **Medium & Dimensions:** Acrylic (5ft x 4ft) • 60 × 48 in (152 × 122 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-28. Rendered in Acrylic (5ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-northern-friend' THEN '[[index|← Return to Master Catalog Index]]

# The Northern Friend

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-28
> **Medium & Dimensions:** - (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Archived • **Surface:** Mixed media archival master

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-28. Rendered in signature mixed media (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'a-trip-to-boozeville' THEN '[[index|← Return to Master Catalog Index]]

# A Trip to Boozeville

![[a-trip-to-boozeville-copy.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'agave-patch' THEN '[[index|← Return to Master Catalog Index]]

# Agave Patch

![[e.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (20in x 28in) • 20 × 28 in (51 × 71 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (20in x 28in) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'beaver-holiday' THEN '[[index|← Return to Master Catalog Index]]

# Beaver Holiday

![[Beaver-Holiday-copy.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'blind-monkey' THEN '[[index|← Return to Master Catalog Index]]

# Blind Monkey

![[blind-monkey-copy.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (28in x 20in) • 28 × 20 in (71 × 51 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (28in x 20in) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'cave-dance' THEN '[[index|← Return to Master Catalog Index]]

# Cave Dance

![[cave-dance-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'chemico' THEN '[[index|← Return to Master Catalog Index]]

# Chemico

![[CHEMICO-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'closing-night' THEN '[[index|← Return to Master Catalog Index]]

# Closing Night

![[closing-night-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'clown-snacks' THEN '[[index|← Return to Master Catalog Index]]

# Clown Snacks

![[l.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 3.5ft) • 60 × 42 in (152 × 107 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 3.5ft) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'cocoa-bear-cereal' THEN '[[index|← Return to Master Catalog Index]]

# Cocoa Bear Cereal

![[r.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 3.5ft) • 60 × 42 in (152 × 107 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 3.5ft) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'cornflower' THEN '[[index|← Return to Master Catalog Index]]

# Cornflower

![[cornflower-12.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (30in x 39in) • 30 × 39 in (76 × 99 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (30in x 39in) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'dairy-gossip' THEN '[[index|← Return to Master Catalog Index]]

# Dairy Gossip

![[dairygossip-.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (14in x 24in) • 14 × 24 in (36 × 61 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (14in x 24in) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'drebbles' THEN '[[index|← Return to Master Catalog Index]]

# Drebbles

![[drebbles-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 3.5ft) • 60 × 42 in (152 × 107 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 3.5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'el-p-jaro-de-los-dulces-m-gicos' THEN '[[index|← Return to Master Catalog Index]]

# El Pájaro de los Dulces Mágicos

![[el-pajaro-de-los-dulces-magicos-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'greasy-todd' THEN '[[index|← Return to Master Catalog Index]]

# Greasy Todd

![[greasytodd-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 3.5ft) • 60 × 42 in (152 × 107 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 3.5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'harvest-orange' THEN '[[index|← Return to Master Catalog Index]]

# Harvest Orange

![[harvestorange-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 3.5ft) • 60 × 42 in (152 × 107 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 3.5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'heavenly-ham' THEN '[[index|← Return to Master Catalog Index]]

# Heavenly Ham

![[heavenlyham-copy.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 3.5ft) • 60 × 42 in (152 × 107 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 3.5ft) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'hell-party' THEN '[[index|← Return to Master Catalog Index]]

# Hell Party

![[Hell-Party-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'invasion-of-the-drunks' THEN '[[index|← Return to Master Catalog Index]]

# Invasion of the Drunks

![[invasion-of-the-drunks-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'issy-the-atomic-companion' THEN '[[index|← Return to Master Catalog Index]]

# Issy: The Atomic Companion

![[Issy-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'jungle-bust' THEN '[[index|← Return to Master Catalog Index]]

# Jungle Bust

![[Jungle-bust-el-5-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (30in x 39in) • 30 × 39 in (76 × 99 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (30in x 39in) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'jungle-tempo' THEN '[[index|← Return to Master Catalog Index]]

# Jungle Tempo

![[Jungle-Tempo-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'boyhood-explorers' THEN '[[index|← Return to Master Catalog Index]]

# Boyhood Explorers

![[boyhood-explorers-6.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'killagor' THEN '[[index|← Return to Master Catalog Index]]

# Killagor

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 12ft) • 60 × 144 in (152 × 366 cm)
> **Status:** Archived • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 12ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'long-beach-short-stop' THEN '[[index|← Return to Master Catalog Index]]

# Long Beach Short Stop

![[long-beach-short-stop-6.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'marooned' THEN '[[index|← Return to Master Catalog Index]]

# Marooned

![[marooned-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'marshmallow-pops' THEN '[[index|← Return to Master Catalog Index]]

# Marshmallow Pops

![[marshmallowpops-copy.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 3.5ft) • 60 × 42 in (152 × 107 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 3.5ft) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'mogul-cigarettes' THEN '[[index|← Return to Master Catalog Index]]

# Mogul Cigarettes

![[mogul-cigarettes-copy.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (21.5in x 14.5in) • 22 × 15 in (56 × 38 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (21.5in x 14.5in) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'monkey-sunset' THEN '[[index|← Return to Master Catalog Index]]

# Monkey Sunset

![[Monkey-Sunset-copy.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (20in x 17in) • 20 × 17 in (51 × 43 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (20in x 17in) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'old-salt' THEN '[[index|← Return to Master Catalog Index]]

# Old Salt

![[oldsalt-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 3.5ft) • 60 × 42 in (152 × 107 cm)
> **Status:** Sold • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 3.5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'raintree-county' THEN '[[index|← Return to Master Catalog Index]]

# Raintree County

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (5ft x 7ft) • 60 × 84 in (152 × 213 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (5ft x 7ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'random-house' THEN '[[index|← Return to Master Catalog Index]]

# Random House

![[random-house-6.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'silent-flute' THEN '[[index|← Return to Master Catalog Index]]

# Silent Flute

![[l.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (25in x 14in) • 25 × 14 in (64 × 36 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (25in x 14in) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'southern-belle' THEN '[[index|← Return to Master Catalog Index]]

# Southern Belle

![[southern-belle-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (30in x 39in) • 30 × 39 in (76 × 99 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (30in x 39in) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'square-eggs' THEN '[[index|← Return to Master Catalog Index]]

# Square Eggs

![[r.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'steamy-the-flavor-genie' THEN '[[index|← Return to Master Catalog Index]]

# Steamy the Flavor Genie

![[Steamy-the-flavor-genie-copy.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'strange-delights' THEN '[[index|← Return to Master Catalog Index]]

# Strange Delights

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'takodon' THEN '[[index|← Return to Master Catalog Index]]

# Takodon

![[k.jpg]]

> **Kaiju & Monster Universe** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 12ft) • 60 × 144 in (152 × 366 cm)
> **Status:** Archived • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 12ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'tales-of-a-chinese-sailor' THEN '[[index|← Return to Master Catalog Index]]

# Tales of a Chinese Sailor

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 3ft) • 48 × 36 in (122 × 91 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 3ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-18-000th-hole' THEN '[[index|← Return to Master Catalog Index]]

# The 18,000th Hole

![[l.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-aquarium' THEN '[[index|← Return to Master Catalog Index]]

# The Aquarium

![[the-aquarium-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-blue-elephant-lounge' THEN '[[index|← Return to Master Catalog Index]]

# The Blue Elephant Lounge

![[The-blue-elephant-lounge-.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-blue-hour' THEN '[[index|← Return to Master Catalog Index]]

# The Blue Hour

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-brimstone-club' THEN '[[index|← Return to Master Catalog Index]]

# The Brimstone Club

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-butter-and-egg-man' THEN '[[index|← Return to Master Catalog Index]]

# The Butter and Egg Man

![[r.jpg]]

> **Vintage Advertising & Commercial Ephemera** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (30in x 39in) • 30 × 39 in (76 × 99 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (30in x 39in) exploring themes of vintage advertising & commercial ephemera. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-copper-state' THEN '[[index|← Return to Master Catalog Index]]

# The Copper State

![[the-copper-state-6.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-drunkenville-carnival' THEN '[[index|← Return to Master Catalog Index]]

# The Drunkenville Carnival

![[The-Drunkeville-Carnival-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-film-student' THEN '[[index|← Return to Master Catalog Index]]

# The Film Student

![[l.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-great-all-stars' THEN '[[index|← Return to Master Catalog Index]]

# The Great All Stars

![[THE-GREAT-ALL-STARS-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (16in x 24in) • 16 × 24 in (41 × 61 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (16in x 24in) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-hell-that-is-monkey-island' THEN '[[index|← Return to Master Catalog Index]]

# The Hell that is Monkey Island

![[l.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-hunger-artist' THEN '[[index|← Return to Master Catalog Index]]

# The Hunger Artist

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-hunting-accident' THEN '[[index|← Return to Master Catalog Index]]

# The Hunting Accident

![[the-hunting-accident-13-x-16-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-midwood-seamstress' THEN '[[index|← Return to Master Catalog Index]]

# The Midwood Seamstress

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-niece-of-murder-she-wrote' THEN '[[index|← Return to Master Catalog Index]]

# The Niece of ''Murder, She Wrote''

![[the-niece-of-murder-she-wrote-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-red-mood' THEN '[[index|← Return to Master Catalog Index]]

# The Red Mood

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (-) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-sound-of-the-wb' THEN '[[index|← Return to Master Catalog Index]]

# The Sound of the WB

![[f.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 5ft) • 48 × 60 in (122 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-watering-hole' THEN '[[index|← Return to Master Catalog Index]]

# The Watering Hole

![[The-watering-hole-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'tonga-joy' THEN '[[index|← Return to Master Catalog Index]]

# Tonga Joy

![[a.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Enamel (5ft x 12ft) • 60 × 144 in (152 × 366 cm)
> **Status:** Archived • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Enamel (5ft x 12ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'tuesday-charmer' THEN '[[index|← Return to Master Catalog Index]]

# Tuesday Charmer

![[Tuesday-Charmer6.5-x8.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (30in x 39in) • 30 × 39 in (76 × 99 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (30in x 39in) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'tuffy-and-the-imaginary-flying-cat-head' THEN '[[index|← Return to Master Catalog Index]]

# Tuffy and the Imaginary Flying Cat Head

![[r.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (4ft x 4ft) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'wisdom-coffee' THEN '[[index|← Return to Master Catalog Index]]

# Wisdom Coffee

![[f.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-27
> **Medium & Dimensions:** Acrylic (22.5in x 13.5in) • 23 × 14 in (58 × 36 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-27. Rendered in Acrylic (22.5in x 13.5in) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'blue-nile' THEN '[[index|← Return to Master Catalog Index]]

# Blue Nile

![[bluenilecropped-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'chivonyx-and-ganzitodon' THEN '[[index|← Return to Master Catalog Index]]

# Chivonyx and Ganzitodon

![[d.jpg]]

> **Kaiju & Monster Universe** — Produced 2011-01-26
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Enamel (3.5ft x 5ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'dinosaur-land' THEN '[[index|← Return to Master Catalog Index]]

# Dinosaur Land

![[dinolandcropped-copy1.jpg]]

> **Kaiju & Monster Universe** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 6ft) • 48 × 72 in (122 × 183 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 6ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'frog-tea' THEN '[[index|← Return to Master Catalog Index]]

# Frog Tea

![[r.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (-) • 36 × 48 in (91 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (-) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'junga-ray' THEN '[[index|← Return to Master Catalog Index]]

# Junga Ray

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-26
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Archived • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'jungle-land' THEN '[[index|← Return to Master Catalog Index]]

# Jungle Land

![[l.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (5ft x 5ft) • 60 × 60 in (152 × 152 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'leisure-time' THEN '[[index|← Return to Master Catalog Index]]

# Leisure Time

![[leisuretimecropped-copy1.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'masons' THEN '[[index|← Return to Master Catalog Index]]

# Masons

![[masonscropped-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'near-arrangement' THEN '[[index|← Return to Master Catalog Index]]

# Near Arrangement

![[near-arrangement-copy.jpg]]

> **Modernist Parody & Fine Art Tribute** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 3ft) • 48 × 36 in (122 × 91 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 3ft) exploring themes of modernist parody & fine art tribute. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'normal-gods' THEN '[[index|← Return to Master Catalog Index]]

# Normal Gods

![[normal-gods-copy.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 3ft) • 48 × 36 in (122 × 91 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 3ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'quadroclops' THEN '[[index|← Return to Master Catalog Index]]

# Quadroclops

![[r.jpg]]

> **Kaiju & Monster Universe** — Produced 2011-01-26
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Enamel (3.5ft x 5ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'regador-v' THEN '[[index|← Return to Master Catalog Index]]

# Regador V

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-26
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Enamel (3.5ft x 5ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'ring-of-horns' THEN '[[index|← Return to Master Catalog Index]]

# Ring of Horns

![[r.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 4ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-cats-of-the-colosseum' THEN '[[index|← Return to Master Catalog Index]]

# The Cats of the Colosseum

![[the-cats-of-the-colloseum-copy3.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 3ft) • 48 × 36 in (122 × 91 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 3ft) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-dawn-of-the-dinosaur' THEN '[[index|← Return to Master Catalog Index]]

# The Dawn of the Dinosaur

![[dinolandtwocropped-copy.jpg]]

> **Kaiju & Monster Universe** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 4ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'the-production' THEN '[[index|← Return to Master Catalog Index]]

# The Production

![[the-production-copy.jpg]]

> **Modernist Parody & Fine Art Tribute** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 3ft) • 48 × 36 in (122 × 91 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 3ft) exploring themes of modernist parody & fine art tribute. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'trimegadon' THEN '[[index|← Return to Master Catalog Index]]

# Trimegadon

![[r.jpg]]

> **Kaiju & Monster Universe** — Produced 2011-01-26
> **Medium & Dimensions:** Enamel (3.5ft x 5ft) • 42 × 60 in (107 × 152 cm)
> **Status:** Available • **Surface:** Enamel on steel plate with protective UV topcoat

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Enamel (3.5ft x 5ft) exploring themes of kaiju & monster universe. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN 'wise-bird' THEN '[[index|← Return to Master Catalog Index]]

# Wise Bird

![[wisebirdcropped-copy.jpg]]

> **Anthropomorphic & Fable Critters** — Produced 2011-01-26
> **Medium & Dimensions:** Acrylic (4ft x 4ft) • 48 × 48 in (122 × 122 cm)
> **Status:** Sold • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-26. Rendered in Acrylic (4ft x 4ft) exploring themes of anthropomorphic & fable critters. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
    WHEN '2010-rendezvous-in-chinatown' THEN '[[index|← Return to Master Catalog Index]]

# 2010: Rendezvous in Chinatown

![[2.jpg]]

> **Pop Surrealism & Mid-Century Neo-Retro** — Produced 2011-01-24
> **Medium & Dimensions:** Acrylic (4ft x 3ft) • 48 × 36 in (122 × 91 cm)
> **Status:** Available • **Surface:** Acrylic on Baltic birch wooden panel

## Artwork Description

Original masterwork by Rory Skagen created on 2011-01-24. Rendered in Acrylic (4ft x 3ft) exploring themes of pop surrealism & mid-century neo-retro. Features Skagen''s distinctive saturated palette, hyper-graphic linework, and evocative mid-century Americana pop-surrealism.'
  END,
  updated_at = now()
WHERE narrative IS NULL OR narrative = '';

-- 1b. Graceful starter narrative for any row with no bundled content
UPDATE public.artworks
SET narrative = '# ' || title || E'\n\nOriginal painting from the Rory Skagen Studio catalog.',
    updated_at = now()
WHERE narrative IS NULL OR narrative = '';

-- 2. Image ref backfill: replace /images/N.svg placeholders with the real
--    image filename refs (clients resolve URLs via the asset resolver)
UPDATE public.artworks
SET image_url = CASE slug
    WHEN 'gianondor' THEN 'gianondor.jpg'
    WHEN 'empopatya' THEN 'empopatya.jpg'
    WHEN 'gaurdon' THEN 'gaurdon.jpg'
    WHEN 'gondoleu' THEN 'gondeoleu.jpg'
    WHEN 'jobar' THEN 'jobar.jpg'
    WHEN 'kondowari' THEN 'kondowari.jpg'
    WHEN 'meiwaku' THEN 'meiwaku.jpg'
    WHEN 'odoroita-sakana' THEN 'OdoritaSakana.jpg'
    WHEN 'osore' THEN 'osore.jpg'
    WHEN 'austin-skyline-2019' THEN 'austin2019-copy.jpg'
    WHEN 'kemuri' THEN 'kemuri.jpg'
    WHEN 'the-persistence-of-cats' THEN '2019cats-copy.jpg'
    WHEN 'today-atomic-sunrise' THEN '2019today-copy.jpg'
    WHEN 'cyborg-robots-and-aliens' THEN 'robot-copy-1.jpg'
    WHEN 'the-martian-ii' THEN 'themartian2-copy.jpg'
    WHEN 'the-martian' THEN 'themartian1-copy.jpg'
    WHEN 'the-carters' THEN 'thecarters.jpg'
    WHEN 'an-insincere-call' THEN 'sound-of-the-WB-copy.jpg'
    WHEN 'arachforun' THEN 'starwars-Recovered-copy.jpg'
    WHEN 'gleesnod-and-collasaur' THEN 'octodino-Recovered-copy.jpg'
    WHEN 'gnarldred' THEN 'Steamy-the-flavor-genie-copy.jpg'
    WHEN 'kelzon-v' THEN 'Jungle-bust-el-5-copy.jpg'
    WHEN 'scaramouche' THEN 'Scaramouche-copy.jpg'
    WHEN 'the-broken-record' THEN 'brokenrecord-copy.jpg'
    WHEN 'the-greeting-card-machine' THEN 'greetingcardmachine-copy.jpg'
    WHEN 'austin-78704-south-austin-zip' THEN '78704.jpg'
    WHEN 'austin-postcard' THEN 'austinpostcard.jpg'
    WHEN 'greetings-from-austin' THEN 'GreetingsfromAustin.jpg'
    WHEN 'greetings-from-texas' THEN 'GreetingsfromTexas.jpg'
    WHEN 'jigoku' THEN 'jigoku.jpg'
    WHEN 'kirunam' THEN 'r.jpg'
    WHEN 'misakimo' THEN 'k.jpg'
    WHEN 'terrordon' THEN 'terrordon.jpg'
    WHEN 'utaho' THEN 'utaho.jpg'
    WHEN 'cry-sing-lon' THEN 'r.jpg'
    WHEN 'austin-camouflage' THEN 'l.jpg'
    WHEN 'austin-carnival' THEN 'r.jpg'
    WHEN 'beat-bop' THEN 'beatbop.jpg'
    WHEN 'jumbo-portions' THEN 'r.jpg'
    WHEN 'marcia-ball' THEN 'r.jpg'
    WHEN 'pollack-jr' THEN 'pollockjr.jpg'
    WHEN 'the-balloon-cats-ii' THEN 'l.jpg'
    WHEN 'the-teapot-ride' THEN 'r.jpg'
    WHEN 'women-and-ladders' THEN 'r.jpg'
    WHEN 'rothko-jr' THEN 'rothmonster-copy.jpg'
    WHEN 'hatari-angani' THEN 'hatari-angani.jpg'
    WHEN 'mao-mao-ting' THEN 'mao-mao-ting.jpg'
    WHEN 'maakclops' THEN 'maakclops.jpg'
    WHEN 'ocamehocta' THEN 'ocamehocta.jpg'
    WHEN 'nangon-and-sadas' THEN 'nangon-and-sadas.jpg'
    WHEN 'the-end-of-austin' THEN 'f.jpg'
    WHEN 'adventures-in-illustration' THEN 'adventures-in-illustration-copy.jpg'
    WHEN 'heartbreak-forest' THEN 'heartbreak-forest-copy.jpg'
    WHEN 'mid-flight-connection' THEN 'midflight-connection-copy.jpg'
    WHEN 'quo-quan-dang' THEN 'd.jpg'
    WHEN 'the-cat-bird-seat' THEN 'the-catbird-seat-copy.jpg'
    WHEN 'the-narrative' THEN 'the-narrative.jpg'
    WHEN 'the-northern-friend' THEN 'r.jpg'
    WHEN 'a-trip-to-boozeville' THEN 'a-trip-to-boozeville-copy.jpg'
    WHEN 'agave-patch' THEN 'e.jpg'
    WHEN 'beaver-holiday' THEN 'Beaver-Holiday-copy.jpg'
    WHEN 'blind-monkey' THEN 'blind-monkey-copy.jpg'
    WHEN 'cave-dance' THEN 'cave-dance-copy.jpg'
    WHEN 'chemico' THEN 'CHEMICO-copy.jpg'
    WHEN 'closing-night' THEN 'closing-night-copy.jpg'
    WHEN 'clown-snacks' THEN 'l.jpg'
    WHEN 'cocoa-bear-cereal' THEN 'r.jpg'
    WHEN 'cornflower' THEN 'cornflower-12.jpg'
    WHEN 'dairy-gossip' THEN 'dairygossip-.jpg'
    WHEN 'drebbles' THEN 'drebbles-copy.jpg'
    WHEN 'el-p-jaro-de-los-dulces-m-gicos' THEN 'el-pajaro-de-los-dulces-magicos-copy.jpg'
    WHEN 'greasy-todd' THEN 'greasytodd-copy.jpg'
    WHEN 'harvest-orange' THEN 'harvestorange-copy.jpg'
    WHEN 'heavenly-ham' THEN 'heavenlyham-copy.jpg'
    WHEN 'hell-party' THEN 'Hell-Party-copy.jpg'
    WHEN 'invasion-of-the-drunks' THEN 'invasion-of-the-drunks-copy.jpg'
    WHEN 'issy-the-atomic-companion' THEN 'Issy-copy.jpg'
    WHEN 'jungle-bust' THEN 'Jungle-bust-el-5-copy.jpg'
    WHEN 'jungle-tempo' THEN 'Jungle-Tempo-copy.jpg'
    WHEN 'boyhood-explorers' THEN 'boyhood-explorers-6.jpg'
    WHEN 'killagor' THEN 'r.jpg'
    WHEN 'long-beach-short-stop' THEN 'long-beach-short-stop-6.jpg'
    WHEN 'marooned' THEN 'marooned-copy.jpg'
    WHEN 'marshmallow-pops' THEN 'marshmallowpops-copy.jpg'
    WHEN 'mogul-cigarettes' THEN 'mogul-cigarettes-copy.jpg'
    WHEN 'monkey-sunset' THEN 'Monkey-Sunset-copy.jpg'
    WHEN 'old-salt' THEN 'oldsalt-copy.jpg'
    WHEN 'raintree-county' THEN 'r.jpg'
    WHEN 'random-house' THEN 'random-house-6.jpg'
    WHEN 'silent-flute' THEN 'l.jpg'
    WHEN 'southern-belle' THEN 'southern-belle-copy.jpg'
    WHEN 'square-eggs' THEN 'r.jpg'
    WHEN 'steamy-the-flavor-genie' THEN 'Steamy-the-flavor-genie-copy.jpg'
    WHEN 'strange-delights' THEN 'r.jpg'
    WHEN 'takodon' THEN 'k.jpg'
    WHEN 'tales-of-a-chinese-sailor' THEN 'r.jpg'
    WHEN 'the-18-000th-hole' THEN 'l.jpg'
    WHEN 'the-aquarium' THEN 'the-aquarium-copy.jpg'
    WHEN 'the-blue-elephant-lounge' THEN 'The-blue-elephant-lounge-.jpg'
    WHEN 'the-blue-hour' THEN 'r.jpg'
    WHEN 'the-brimstone-club' THEN 'r.jpg'
    WHEN 'the-butter-and-egg-man' THEN 'r.jpg'
    WHEN 'the-copper-state' THEN 'the-copper-state-6.jpg'
    WHEN 'the-drunkenville-carnival' THEN 'The-Drunkeville-Carnival-copy.jpg'
    WHEN 'the-film-student' THEN 'l.jpg'
    WHEN 'the-great-all-stars' THEN 'THE-GREAT-ALL-STARS-copy.jpg'
    WHEN 'the-hell-that-is-monkey-island' THEN 'l.jpg'
    WHEN 'the-hunger-artist' THEN 'r.jpg'
    WHEN 'the-hunting-accident' THEN 'the-hunting-accident-13-x-16-copy.jpg'
    WHEN 'the-midwood-seamstress' THEN 'r.jpg'
    WHEN 'the-niece-of-murder-she-wrote' THEN 'the-niece-of-murder-she-wrote-copy.jpg'
    WHEN 'the-red-mood' THEN 'r.jpg'
    WHEN 'the-sound-of-the-wb' THEN 'f.jpg'
    WHEN 'the-watering-hole' THEN 'The-watering-hole-copy.jpg'
    WHEN 'tonga-joy' THEN 'a.jpg'
    WHEN 'tuesday-charmer' THEN 'Tuesday-Charmer6.5-x8.jpg'
    WHEN 'tuffy-and-the-imaginary-flying-cat-head' THEN 'r.jpg'
    WHEN 'wisdom-coffee' THEN 'f.jpg'
    WHEN 'blue-nile' THEN 'bluenilecropped-copy.jpg'
    WHEN 'chivonyx-and-ganzitodon' THEN 'd.jpg'
    WHEN 'dinosaur-land' THEN 'dinolandcropped-copy1.jpg'
    WHEN 'frog-tea' THEN 'r.jpg'
    WHEN 'junga-ray' THEN 'r.jpg'
    WHEN 'jungle-land' THEN 'l.jpg'
    WHEN 'leisure-time' THEN 'leisuretimecropped-copy1.jpg'
    WHEN 'masons' THEN 'masonscropped-copy.jpg'
    WHEN 'near-arrangement' THEN 'near-arrangement-copy.jpg'
    WHEN 'normal-gods' THEN 'normal-gods-copy.jpg'
    WHEN 'quadroclops' THEN 'r.jpg'
    WHEN 'regador-v' THEN 'r.jpg'
    WHEN 'ring-of-horns' THEN 'r.jpg'
    WHEN 'the-cats-of-the-colosseum' THEN 'the-cats-of-the-colloseum-copy3.jpg'
    WHEN 'the-dawn-of-the-dinosaur' THEN 'dinolandtwocropped-copy.jpg'
    WHEN 'the-production' THEN 'the-production-copy.jpg'
    WHEN 'trimegadon' THEN 'r.jpg'
    WHEN 'wise-bird' THEN 'wisebirdcropped-copy.jpg'
    WHEN '2010-rendezvous-in-chinatown' THEN '2.jpg'
  END,
  updated_at = now()
WHERE image_url IS NULL OR image_url LIKE '/images/%';

-- 3. Restore the studio's default hero-slider selection
UPDATE public.artworks
SET hero_slider = true, updated_at = now()
WHERE slug IN ('greetings-from-austin', 'godzilla-austin', 'king-kong-austin', 'drive-in-theatre', 'retro-robot-sign', 'atomic-cocktail-lounge', 'kirunan', 'terrordon', '2010-rendezvous-in-chinatown', 'the-cats-of-the-colosseum') AND hero_slider = false;

-- 4. Seed bundled pages (upsert; admin edits in the DB always win afterwards)
INSERT INTO public.pages (slug, title, content)
VALUES
  ('about', 'About', '---
title: About
date: ''2011-01-24''
slug: about
type: page
status: Archived
location: Austin, TX
tags:
- art/location/austin
- art/status/archived
---

[[index|← Return to Resource Map Index]]

---

![[Rory-Skagen-Photo.jpg]]

<p style="text-align: left;">Rory Skagen moved to Austin, TX  in 1992 and began working as a professional artist in 1994. This websites contains the highlights of the fine art side of his career since 1999. Rory''s paintings reflect his appreciation of the "visual concept and the art of ideas." Although the content frequently changes, Rory''s imagery usually maintains a sense of absurd optimism.</p>
<p style="text-align: left;">Beside his focus on fine art. Rory Skagen freelances as a commercial artist. Over the years he has created a line of art products that are available at Christmas at the Blue Genie Art Bazaar, and the Armadillo Christmas Bazaar, as well as year round at the upcoming Blue Genie store at the popular tourist destination Oasis, Texas.</p>
<p style="text-align: left;">For inquiries regarding the purchase of one of Rory''s paintings please contact him via email or telephone from the [Contact ](http:roryskagen.local/contact/)page.</p>
<p style="text-align: left;">And for additional information about the art of Rory Skagen visit his websites:</p>
Central Texas Murals: [centraltexasmurals.com](http://centraltexasmurals.com/)  
Skagen Designs (coming soon): [skagendesign.com](http://skagendesign.com/)  
Blue Genie Art Bazaar: [bluegenieartbazaar.com](http://bluegenieartbazaar.com/)
'),
  ('contact', 'Contact', '---
title: Contact
date: ''2011-01-25''
slug: contact
type: page
status: Archived
location: Austin, TX
tags:
- art/location/austin
- art/status/archived
---

[[index|← Return to Resource Map Index]]

---

![[Rory-Skagen-Photo.jpg]]

# **Rory Skagen**

**<span style="color: #484d79;">Phone: </span>**512-916-9847

**<span style="color: #484d79;">Email: </span>**[rory@bluegenieart.com](mailto:rory@bluegenieart.com)

**<span style="color: #484d79;">Mailing Address:</span>**  
Rory Skagen Art  
2209 S 1st St, Ste F  
Austin TX 78704
'),
  ('commissions', 'Commissions', '---
title: "Commission Guidelines & Public Art"
subtitle: "Custom Canvas Paintings, Neon Installations & Large-Scale Murals"
slug: "commissions"
---

# Commissioning Custom Artwork

Rory Skagen accepts a strictly limited number of private canvas commissions and municipal/commercial public art murals each calendar year.

## 1. Canvas Paintings (Private & Corporate)
- **Scale:** Sizes range from 36" x 48" up to 72" x 120" multi-panel works.
- **Mediums:** Fine oil on Belgian linen, acrylic with palladium/gold metal leaf, and illuminated neon-hybrid canvas.
- **Themes:** Custom roadside Americana, retro Texas architecture, vintage automobile portraits, and atomic-age pop landscapes.
- **Timeline:** Typically 8–14 weeks from concept approval.
- **Pricing:** Inquire with dimensions and desired theme.

## 2. Public & Commercial Murals
As seen in the iconic **[[greetings-from-austin|Greetings from Austin Landmark}]]**, Skagen''s murals are engineered to withstand exterior elements using industrial UV-resistant acrylic silicates and elastomeric masonry primers.

### Process:
1. **Initial Site Survey & Conceptual Brief**
2. **Color Study & Digital Architectural Renderings**
3. **Execution & Sealant Application**

Ready to discuss your project? [[pages/contact|Send a Studio Inquiry]].
'),
  ('exhibitions', 'Exhibitions', '---
title: "Exhibition History & Public Works"
subtitle: "Museum Showings, Gallery Retrospectives & Landmark Installations"
slug: "exhibitions"
---

# Selected Exhibitions & Installations

### Public Landmark Installations
- **1998–Present:** *Greetings from Austin* (South 1st & Annie St, Austin, TX)
- **2014:** *Keep Austin Weird Retro Revival* (Austin Convention Center)
- **2018:** *Lone Star Cosmic Highway* (Willie Nelson Blvd / 2nd Street)
- **2022:** *Texas Neon Odyssey* (East Austin Arts District)

### Solo Exhibitions
- **2024:** *Neon Twilight & Atomic Dreams*, Modern Pop Gallery (Dallas, TX)
- **2023:** *The Open Highway: 30 Years of Texas Pop*, Yard Dog Gallery (Austin, TX)
- **2021:** *Cosmic Armadillo: A Tribute to Austin''s Golden Era*, South Congress Arts (Austin, TX)
- **2019:** *Atomic Sunset: Mid-Century Sci-Fi & Americana*, Desert Modern (Palm Springs, CA)

### Permanent Museum Collections
- Austin Museum of Popular Culture (SouthPop)
- The Wittliff Collections (Texas State University)
- San Antonio Pop Art Foundation
')
ON CONFLICT (slug) DO NOTHING;
